#baseURL = 'http://example.org/'
baseURL = ''
languageCode = 'en-us'
title = 'Blog Post by Tuhin'
theme = 'ananke'


tags = ["Create Website", "Install Software","Github", "DIY Website"]
features = ["website","posts", "shortcodes", "related content", "comments"]

#[related]
#  includeNewer = true
#  threshold = 20
#  toLower = true
#[[related.indices]]
#  applyFilter = false
#  name = 'fragmentrefs'
#  type = 'fragments'
#  weight = 80

resourceDir = "../resources"
canonifyURLs = true

#[markup]
#  defaultMarkdownHandler = 'blackFriday'
#  [markup.blackFriday]
#    hrefTargetBlank = true




DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Tuhin's Blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Tuhin Majumder"
  favicon = "/images/favicon.ico"
  site_logo = "/images/apple-touch-icon.png"
  description = "<LEARN> Anything. </LEARN>"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 3
  body_classes = "avenir bg-washed-yellow"
  keyword = [
  "hugo",
  "seo",
  "blog",
  "website",
  "technical",
  "writing",
  "knowledge",
  "coding",
  "learning",
  "github"
]
#    date_format = "2006"
#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/tuhinmaj"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/tuhinmaj1998"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/tuhin-majumder-764636125/"

[menu]
[[menu.main]]
    name = "Home"
    identifier = "Home"
    weight = 1
    url = "/"

[[menu.main]]
    name = "About"
#    pre = "<i class='fa fa-heart'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "DIY-Website"
#    pre = "<i class='fa fa-heart'></i>"
    weight = 3
    identifier = "DIY-Website"
    url = "/post/diy-website"

[[menu.main]]
    name = "Subscribe"
#    pre = "<i class='fa fa-heart'></i>"
    weight = 4
    identifier = "Subscribe"
    url = "/subscribe"

[[menu.main]]
    parent = "DIY-Website"
    name = "Introduction"
    identifier = "Intro"
    url = "/post/diy-website/intro"

[[menu.main]]
    parent = "DIY-Website"
    name = "Static Website"
    identifier = "Static Web"
    url = "/post/diy-website/static-website"


[[menu.main]]
    parent = "DIY-Website"
    name = "Set Up Environment"
    identifier = "Set Env"
    url = "/post/diy-website/setting_up_env"